// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewApp.Models;

namespace ReviewApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20181103200531_AddNewReviews")]
    partial class AddNewReviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReviewApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = 1, Name = "Sci-Fi" },
                        new { Id = 2, Name = "Fantasy" },
                        new { Id = 3, Name = "Action" },
                        new { Id = 4, Name = "RomCom" }
                    );
                });

            modelBuilder.Entity("ReviewApp.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltPicText");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Content");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new { Id = 1, AltPicText = "Venom", CategoryId = 3, Content = "The critics said this movie sucked! I haven't seen it yet but Neko said it was awesome! I guess I need to go see it myself.", ImageURL = "/images/Venom.jpg", Title = "Venom" },
                        new { Id = 2, AltPicText = "Harry Potter", CategoryId = 2, Content = "Best movie EVER!!! Based on the best book series ever! I love this movie. Go watch it if you haven't.", ImageURL = "/images/HarryPotter.jpg", Title = "Harry Potter and the Philosopher's Stone" },
                        new { Id = 3, AltPicText = "Guardians", CategoryId = 1, Content = "Hilarious! A must see movie! High quality writing just like every other MCU movie. If they don't make a third one, my heart will break.", ImageURL = "/images/Guardians.jpg", Title = "Guardians of the Galaxy" },
                        new { Id = 4, AltPicText = "Iron Man", CategoryId = 3, Content = "This movie is when the Marvel Cinematic Universe really started to come alive for me.", ImageURL = "/images/Guardians.jpg", Title = "Iron Man" },
                        new { Id = 5, AltPicText = "Holiday Calendar", CategoryId = 4, Content = "This movie is your typical cliche romantic comedy but that didn't stop me from loving it.", ImageURL = "/images/Guardians.jpg", Title = "The Holiday Calendar" },
                        new { Id = 6, AltPicText = "Eternal Sunshine", CategoryId = 4, Content = "One of the best movies I've ever seen! It is not a typical cliche romantic comedy and it has the best performance of Jim Carey's career.", ImageURL = "/images/Guardians.jpg", Title = "Eternal Sunshine of the Spotless Mind" },
                        new { Id = 7, AltPicText = "Avatar", CategoryId = 2, Content = "This is a great movie with something for everyone.", ImageURL = "/images/Guardians.jpg", Title = "Avatar" },
                        new { Id = 8, AltPicText = "Arrival", CategoryId = 1, Content = "While many people raved about how awesome this movie was and how great the ending was, I have to say that I was disappointed because I saw the ending coming from a mile away.", ImageURL = "/images/Guardians.jpg", Title = "Arrival" }
                    );
                });

            modelBuilder.Entity("ReviewApp.Models.Review", b =>
                {
                    b.HasOne("ReviewApp.Models.Category", "Category")
                        .WithMany("Reviews")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
